### ISSUE TITLE
Unable to access data

### ISSUE THREAD

**Issue by jacobvinoo** [trynthink/buildingsdatasets#9]
Links not working 

http://trynthink.github.io/buildingsdatasets/show.html?title_id=buildings-energy-data-book

**Comment by trynthink** [comment]
Thanks for bringing this broken link to our attention. The Buildings Energy Data Book is now available from OpenEI: https://openei.org/doe-opendata/dataset/buildings-energy-data-book. We'll be updating the resource link shortly.
